"""Glyphen aus Segoe Fluent Icons (Windows 11) bzw. Segoe MDL2 Assets (Windows 10).

Beide Schriften verwenden für diese Symbole dieselben Codepunkte. Fehlen
beide Schriften, blenden die Widgets Symbole aus statt Ersatzzeichen zu zeigen.
"""

GLOBAL_NAV = ""  # GlobalNavigationButton (Hamburger)
CHEVRON_DOWN = ""
CHEVRON_UP = ""
CHEVRON_RIGHT = ""
EDIT = ""
ADD = ""
CANCEL = ""  # Schließen
MORE = ""
SETTINGS = ""
CONTACT = ""
MEMO = ""
PERSONALIZE = ""
SYSTEM = ""
BRIGHTNESS = ""  # Hell
QUIET_HOURS = ""  # Dunkel
COLOR = ""
REFRESH = ""
DELETE = ""
SAVE = ""
PLAY = ""
MEGAPHONE = ""
UNDO = ""
WARNING = ""
PAGE = ""
HISTORY = ""
RECENT = ""
FOLDER_OPEN = ""
CLEAR = ""
SYNC = ""
HELP = ""
DOCUMENT = ""
OPEN_IN_WINDOW = ""
RENAME = ""
ORIENTATION = ""
FOLDER = ""
PICTURE = ""
FONT = ""
ALIGN_CENTER = ""
ALIGN_LEFT = ""
OPEN_FILE = ""
REPEAT_ALL = ""
LIBRARY = ""
ACCEPT = ""
BULLETED_LIST = ""
PHOTO = ""
COMPLETED = ""
INFO = ""
CHECK_MARK = ""
KEYBOARD = ""
RULER = ""
LIGHTBULB = ""
