"""Glyphen aus Segoe Fluent Icons (Windows 11) bzw. Segoe MDL2 Assets (Windows 10).

Beide Schriften verwenden für diese Symbole dieselben Codepunkte. Fehlen
beide Schriften, blenden die Widgets Symbole aus statt Ersatzzeichen zu zeigen.
"""

GLOBAL_NAV = ""  # GlobalNavigationButton (Hamburger)
CHEVRON_DOWN = ""
CHEVRON_UP = ""
CHEVRON_RIGHT = ""
EDIT = ""
ADD = ""
CANCEL = ""  # Schließen
MORE = ""
SETTINGS = ""
CONTACT = ""
MEMO = ""
PERSONALIZE = ""
SYSTEM = ""
BRIGHTNESS = ""  # Hell
QUIET_HOURS = ""  # Dunkel
COLOR = ""
REFRESH = ""
DELETE = ""
SAVE = ""
PLAY = ""
MEGAPHONE = ""
UNDO = ""
WARNING = ""
PAGE = ""
HISTORY = ""
RECENT = ""
FOLDER_OPEN = ""
CLEAR = ""
SYNC = ""
HELP = ""
DOCUMENT = ""
OPEN_IN_WINDOW = ""
RENAME = ""
ORIENTATION = ""
FOLDER = ""
PICTURE = ""
FONT = ""
ALIGN_CENTER = ""
ALIGN_LEFT = ""
OPEN_FILE = ""
REPEAT_ALL = ""
LIBRARY = ""
ACCEPT = ""
BULLETED_LIST = ""
PHOTO = ""
COMPLETED = ""
INFO = ""
CHECK_MARK = ""
KEYBOARD = ""
RULER = ""
LIGHTBULB = ""
COPY = "\ue8c8"  # Kopieren
ALIGN_RIGHT = "\ue8e2"
HOME = "\ue80f"  # Startseite
REPAIR = "\ue90f"  # Schraubenschlüssel
PDF = "\uea90"
SHIELD = "\uea18"  # Datenschutz
LOCK = "\ue72e"
UPLOAD = "\ue898"
STOP = "\ue71a"
APPS = "\ue71d"  # Alle Werkzeuge
SEARCH = "\ue721"
PEOPLE = "\ue716"  # Kunden
ADD_FRIEND = "\ue8fa"  # Kundenakte anlegen
MAIL = "\ue715"
ZOOM_IN = "\ue8a3"
ZOOM_OUT = "\ue71f"
CHEVRON_LEFT = "\ue76b"
VIEW = "\ue890"  # Vorschau
LINK = "\ue71b"  # Zuordnung
SWITCH = "\ue8ab"  # Zusammenführen
FIT_PAGE = "\ue9a6"
BACK = "\ue72b"
